apiVersion: apps/v1
kind: Deployment
metadata:
  name: dimp-auth
spec:
  selector:
    matchLabels:
      app: dimp-auth
  template:
    spec:
      containers:
        - name: dimp-auth
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pg-dimp-auth
                  key: fqdn-uri
