apiVersion: v1
kind: Secret
metadata:
    name: dimp-auth-secrets
type: Opaque
stringData:
    DISCORD_CLIENT_ID: ENC[AES256_GCM,data:Lx3PyQseZnDgumOV5oX4Ons3/w==,iv:q6Z1leNPCdE5S5Qk4c62kOuHrFFaikoQ3MBPnF9N4nY=,tag:HP2F0/203DiXrihhhmn7yg==,type:str]
    DISCORD_OAUTH_TOKEN: ENC[AES256_GCM,data:P6HgXAzsvrYRwd64xLKJbTtgYCjqapItMCG7qHzfGOY=,iv:A2J/DqnOtqZM+uvg3yxNzxDXpWdMxqJ+cnFOhS84Wzs=,tag:FMcAg/FWs6MiG1GCi8Vj5g==,type:str]
sops:
    age:
        - recipient: age18z3fy59zgysfr8jj3wlpsha2hjqjwm6glaes29wefxa3fadd6a4qnyh873
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cHZNWWtEQVJZVVpEQlNx
            eHE0YnZTYi9xRkhXeGU4aGI3QXd1WnVBY1VRCkVnYkVYVlpVTktTTmF5bCt0NTEr
            b3I5MFNVUlBMcDBHOEdGZDNPcUhqalEKLS0tIENnemJXZXcvdGpKWS9KMFY1aG5u
            dkhaeFdqaHJWY2lzRjJLaWp6MWxEbTgKDUB40RZxEi/7S0rCfd+7qbK3j3AzOsMR
            IzATt+l4uHFhn/Rd35TIZZIKplXnF7kCnoXIIV0LhPHyhrht3BmbdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T19:31:29Z"
    mac: ENC[AES256_GCM,data:kUwKu7OR4iw+0MVoSpMjs05+4T9uRZan+TeXVXIe4m3efDjWoMQ0JDLtxiKym3PfQdUIvyOixzqroUaXubkw+35T6qzaghwYjVWlgb89Pty4kmW8YeDf1Her9LrTcNYr5Iq0c6A6O4hJ+D6ZgFznq09AWtQPTzbAm1qVxuMKRaA=,iv:Hsb6sDsCDDW9mPIumMmfIHmGYYGe3rTeLscTbd2jvLs=,tag:dqcnESB+YmF1ZPXrGfcXRA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
