fullnameOverride: kube-prometheus-stack

grafana:
  enabled: true

  persistence:
    enabled: true
    type: pvc

    size: 10Gi

    accessModes:
      - ReadWriteOnce

    finalizers:
      - kubernetes.io/pvc-protection

  serviceMonitor:
    enabled: true
    path: "/metrics"

    labels:
      release: kube-prometheus-stack

prometheus:
  enabled: true
  prometheusSpec:
    retentionSize: 30GiB
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 50Gi

alertmanager:
  enabled: true
