apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: flux-system
spec:
  interval: 30m
  releaseName: cnpg
  targetNamespace: cnpg-system
  install:
    createNamespace: true
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.27.0
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
      interval: 12h
