apiVersion: v1
kind: Secret
metadata:
    name: internship-observer-ghcr-pull-secret
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:D34WnwW5lh37gQ3EUGkwcEoy8jbVy9bB9FIAWnjLIyNb1+Grh+tOw/YizgJjX2YlNlQbyajYryyyEL0vqUEYJJ2I2bfHoc7uBFeih5OpLMeJSXZd3fIMV/Gi3T0rcZ+QV+L5Q7az6IrBPbfQDPmv2zg/gGl149wejg9uRur4QYlhVCrsqr6mt6fz2shh,iv:nFwSC/PcRh46WKsfKHTHaFxHTFGr0BD0QyhWTk7SjfY=,tag:OQiGJ5xg4CXMOSUczvUonw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbmFQeEIwWlFQaThzRTY5
            V0FOSU01WE9xQm1sdnFyeTVHSklZVDVpQ2drCllYZmQ1YUNSd0RmN1JSTExyQWRv
            U3ZQdkwvempDWk1XZzRSdDVzeU82NE0KLS0tIHpEQm5zcUVLMERRemNmTy9uTGl4
            aGsvRE5zQmlPbTFNTTFiZnYrdjZMcUEKiTQO9VyxQLhWb20s3iUE/Wb4GjA7W5Ai
            NZ20iwwwFzJy5wynVxKaFHwQ9hHDZ48pQgTgQ4NE6y3lHQfxn5Ww2w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nkevsjrus2tls3xr2tf6wzypjzualle59evnrf9ucedphfkrmyxq9x569z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTjlSdFdtNElXQW1uaUlU
            Mjh4ZWRiZ09IdHM4eTZVWFRBMFA4T0p4bWlBCjRoT2FKT3BxV1pTTU9HbnJuY2lx
            dHV0NGxaQTJvZThGVzBsakZ1R01udHcKLS0tIFo1R1RSNXEzSTJSN1F2WGg2ZkhH
            SHZHTEJ3ZU9QVDNReVlMRTNWSTZkd1UKM1KBmYwgr1PCim1E9PglVf+I0bDdrOtD
            Si33iBhPnj38mTinx3UJtlBtDs8+MSd6cku8D/2XHW/HAZWQiAw93g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18z3fy59zgysfr8jj3wlpsha2hjqjwm6glaes29wefxa3fadd6a4qnyh873
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T17:20:26Z"
    mac: ENC[AES256_GCM,data:NiWySdcrs+uwRqGWF7IIgMI9QDOWWbkhZcHM2AQEVmzHqyO59BTz3Hdx+qG3CtHp4gIANT92EOmzOZ8cvWh/KIBVQ1NfgZSt/hms9J49u4YsEp6BhrOPa5OxuIC5C9JKt85fYgNrQxO2323m+h+p2LWwz4bWW3f3dEBHIb6GCbg=,iv:Fywb7Op9WB9Tc7JuiWW6f0pPhDvWFSbKMoFM6o/EsZc=,tag:sMIZTVM2Ozlxr6MRajkr3Q==,type:str]
    version: 3.13.1
