apiVersion: v1
kind: Secret
metadata:
    name: internship-observer-ghcr-pull-secret
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:Dre0tnee480hD71jfFe26KKIZZalqfbc4e0MMzg7Siayl+2+48RPeaFUD2Bdoa/9aIoTzUTmyQQgFGeXyTXw5YvIBwgjlqw7C0fxGTqTI2BYlJUQjz9qTXpb/0btJlAkF4SECzI3cBQiW2GEYvgGs5iW14ryKtfUYjMNTZGCTcQQk7Pp7NHNPXFwKrZO,iv:TMP2pgyFGTUIPwhHYlxDm5j8x9xaX/eilzci3RPRoRo=,tag:NyKW0gsi3fpRF+eXjz3kXA==,type:str]
sops:
    age:
        - recipient: age18z3fy59zgysfr8jj3wlpsha2hjqjwm6glaes29wefxa3fadd6a4qnyh873
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdUN1YThjcnZHVmk0Vjhn
            NVhCSklvQnYwK0N5NDJDbnJwQnVacktGZUdVCmJ3U0k1TkY4YXFKSVhYU1J6OXNO
            MXdaeUxRZFZ1U085ZWJsQ0pZeG9aL1kKLS0tIE1Dd3ZKTW5vYlNML2NFdWZWWXVN
            ZkJRN3J2MjluWXRPVWNkam00MnUxYkEK5HX+ahbmHPizCbLuwxrjvdJYlSj8XoLJ
            dxpD/xBW8RBZ/vLQvEsijtABxql1L3LqpsFbOFWkGYRzMFU0kYdvdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T23:00:44Z"
    mac: ENC[AES256_GCM,data:tvU0PmLRw670ACRFmqLfElA4G5Qmv1V/2YinI23f1RppKF5l133ovFl2f2qP9wlUj0PwhQrw+AZ0M7661EN6QOuKlw/gfDwCgAjWr43fzsUQIGbxKj820TkTTeDPvyA00UbQy7aBpZP+tVzKc7VSOrwTorycN6sxOtbg9C94u/Y=,iv:3MyR5cFY/LvRZ5khq1sP3GVbF3pVm9QLwYU8W/Cfdow=,tag:c7Jb4v44pO4zyZ7WBwl/DQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
