# When updating this secret, please update the corresponding secret in jobs/internship-observer/ghcr-pull-secret.enc.yaml as well.
apiVersion: v1
kind: Secret
metadata:
    name: internship-observer-ghcr-pull-secret
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:xWsOH6dW4BKUctv7fo70ds3SbP8wvGzCvlnTdpBXFjRs6SCA6ONEMbdD7Jk7LmThg+8T3LdaiPnJUOeOOvoSewDeAZeaQtlqDVpi7/ocFGLgkownOERGRHoZ7wUgJ1Oit7jSURVkaFvrRurMTbLgN/nWKnccFw0cBFaKMRI4aR5MOardEC4EgIOLDGPo,iv:xjs2HRL7u9Jf10msG2xQbcTKU4WKWefIINSGaDohIto=,tag:AhV7D8mNBhuFZH3Q1ktM3g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMVpPTHJJcXBhb2FlcFBO
            YllrcHJleVlxenVOS3ltMkVHa2VVOE1vdUFVCk1vYXhialRHMG00a1NjL28ycjBp
            RkRucDVpN0xPNnNUUXFtdWRqVDFaZjQKLS0tIDBXL2JTeU0yVDUvS3Z3VityQTlh
            OXVXb1czcEd5WDVLeFZtS2VxSmJGencK8mi8lbk1d4/xaLuixnUNsw9L6NCmZdIB
            p961pvP3n6szrVTwK+egKjOxLyYWM4QpXLUvXuobqB3fZphyUXLNPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nkevsjrus2tls3xr2tf6wzypjzualle59evnrf9ucedphfkrmyxq9x569z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISno4RW5xQTdKK3B1UnJo
            MldmRW0vdlZ3amxZUzVGeG11bTUvNmllMEdZCm9jVVFVbVBpZ0kxL2pLUGRuMlpn
            YTZ0Q0dBVkJJMk1TeVY2ZldrOThHeW8KLS0tIE0reHVrcDBMUlVoWkRscFlWZHpm
            eGN4MWVQZGZBb01oWTJxbkZNMHdUdDAKW1VMmoqCVfjz0hZo2Yb1fUBydms4InRc
            A9ruUo3yfOj7I3QLo3tn4YDznJln94Ck1gH+vxBTU3qsP8iA9bcm0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18z3fy59zgysfr8jj3wlpsha2hjqjwm6glaes29wefxa3fadd6a4qnyh873
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T17:25:26Z"
    mac: ENC[AES256_GCM,data:zSFZzcZbnprSw1SWcp2JCqgGrbAawG732cUKJHcBVpqPdiPXLGYNmVv8bbRXRMCkxRFotMDJ3A1yoYA8wmfzCa9gwrFUl35PgAFtDs8yeFBjpNYtit7ndSdyn5CEDGIDfN0WhtOhGhkJmqTZKZyTO1OYTcAUkCkVMzvL0PuawwI=,iv:ouI0stXWGeoH34oC4qYsEPe91/Cd6fZauH4X4OKKqwI=,tag:t+fnKKgYGQWwyg39fnQfrw==,type:str]
    version: 3.13.1
