apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: al-dente
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/al-dente/overlays/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
