apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kbw-productsdisplay-backup
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/kbw-productsdisplay/overlays/prod-backup
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
  dependsOn:
    - name: kbw-productsdisplay
