apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kbw-productsdisplay
resources:
  - ../../base
  - namespace.yaml
patches:
  - path: ghcr-pull-secret.enc.yaml
  - path: api-configmap.yaml
  - path: api-secrets.enc.yaml
  - path: ../../../../components/playwright-sidecar.patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: kbw-productsdisplay-api
      # - path: web-configmap.yaml
      # - path: web-secrets.enc.yaml
images:
  # - name: ghcr.io/1spyral/kbw-productsdisplay
  #   newTag: latest
  #   digest: sha256:da09034eae8b1a76b5c08b31f1645f443dc9359b1c857246b06fad455822ab16 # {"$imagepolicy": "flux-system:kbw-productsdisplay:digest"}
  - name: ghcr.io/1spyral/productsdisplay-api
    newTag: latest
    digest: sha256:e6f4102face0aeb4e4648c2a47d4290cbcea0774202e03abe4230ec975cc334d # {"$imagepolicy": "flux-system:kbw-productsdisplay-api:digest"}
