---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-dev
spec:
  instances: 1

  storage:
    size: 50Gi

  managed:
    roles:
      - name: dimp
        ensure: present
        login: true
        passwordSecret:
          name: pg-dev-dimp-auth
