apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secrets
type: Opaque
stringData:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:sCgacSOUvQeWHyNVA10aNMz9qpmKHZrn0+GvcOdX7v6Nh4BFTwiJBtTSRzTZ1atS7THD6E140nU/oPJxqz9Kdg==,iv:cpHm5c3epnX++cCYn/WhnX3XvE1sbyDM4MBtpxR2Hvo=,tag:4r/YUrxOg2MEqJIJMXNulg==,type:str]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:FGk7cF1jTP9Wa3TAh+ZNXq1kb2XWQyaxvMHNCDVW72pKFO/gJEFXa7JxQoqJpEDU5HB8Jovl8D8hgB3LI71LeV9c952iThdiCyhvVaXYgukicmZHFdmrbFYBuIz+Lv3bwUhAnxx36hYz/Zl7,iv:kpOdkZCtwpTd/V0vfkQ8Au6oOgKsGuElYlLf5yOy0Pg=,tag:GXRHuOx9Tv78/1zhwsZnJg==,type:str]
sops:
    age:
        - recipient: age18z3fy59zgysfr8jj3wlpsha2hjqjwm6glaes29wefxa3fadd6a4qnyh873
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bzRnVk5CTU1BWHNPN3lO
            MmVNbFdZUTBoWXdydzhFMmlwOVVNRStvS2dzCkppR0hzNGMzcStnRjJSVTA5SXhI
            T283K3NoamUwYTZsNTJmYmhGQ2VyM0UKLS0tIE14Y3lET0hKRTYwNzVMOFdMczhW
            YXFCRWYyaUFtaVp0Wmg5dnhGUVJGN3cK9wk7vVJWoX6w6tkZTp/QcJ42ZWgThfHT
            XR+he5yyqUPYW8AxAZlTOwE8hiTAjYV9HlJ6/Mz463qaRdcx8wgBzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T17:11:29Z"
    mac: ENC[AES256_GCM,data:ldkJ4EChKqQy8cgIPS8BPDUeaGMIV9TSCnsniEeTSpakdLKj2sA0x0bGOYsA+s6L6Op77HxKnYyiA8NgEM9pIsuhmWqTiYLvEdm8IBK738+oC6DEldOnbTBbs+dyHcseeTCL/Es4D+fNr/BSkOV6mYqzZ80AqHYzrseC2WXBvVg=,iv:FKm/rxttXdvGRfdxL5dIF++8GoiuXLgAJqD0BqenQsA=,tag:Wm/XPHxHwSCX6n5sX7KMag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
