apiVersion: batch/v1
kind: Job
metadata:
  name: db-auth-migrate
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: ghcr.io/1spyral/dimp-auth-migrate
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pg-dimp-auth
                  key: fqdn-uri
