apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
spec:
  backoffLimit: 3 # retry up to 3 times on failure
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: ghcr.io/1spyral/dimp-server-migrate
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: pg-dimp-app
                  key: fqdn-uri
