apiVersion: batch/v1
kind: Job
metadata:
  name: db-server-migrate
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: ghcr.io/1spyral/dimp-server-migrate
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pg-dimp-app
                  key: fqdn-uri
