apiVersion: v1
kind: Secret
metadata:
    name: pg-dimp-auth
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:3HRcuQ==,iv:jrs8lqnzErihCRVWv/Q7hDUJOGCB9toQAYyIYiEw1LQ=,tag:AkXvy4PRdOywHXOWFV/FKA==,type:str]
    password: ENC[AES256_GCM,data:7A1UzeNY9rdQVhccn9dPfhMbSCIeE2wgKbzFivnYGpgHGIe5H5tqYugOI8hUPr12WFo0WUnnieIhLbTnvv3uNg==,iv:jmMkNTOWdG0Q40q7aMc/A8ZCDQdd0oU+OT8TUDvHYcQ=,tag:4/IHxAI2w3coCMacXgdoOg==,type:str]
    fqdn-uri: ENC[AES256_GCM,data:MOxvi8kQiYgSv5v6HDkZGnnCbQayBahRyHnT14dOY9tqO5mxJT9mM6aVkst0UhVb/dXWOtjUT2QyUWeooMChz9iJZGxBs8qOMMyzQevTAdEW0saJLtCvrtEB/jAVH4/VGeYJnfVaeFdSNUHmf2mB7HieFpCyfHJprmc0/a+0mrBKRHhLFN8=,iv:tYhLnBWZbuxvscoUNKMIFdURQ60F7ON27vJj6zdK+I8=,tag:dGtPfoFYQYVvgsA6Gg7MKA==,type:str]
sops:
    age:
        - recipient: age18z3fy59zgysfr8jj3wlpsha2hjqjwm6glaes29wefxa3fadd6a4qnyh873
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRlVkWHBSaDl1QjNiZktN
            U2JiM2cvb1Y0L3Njc3lHZEgycDRFZWhDbDE4CjRLV2RLTkdyTzNubXhnR3pDS05W
            Z0xKK2RjTHNpTlpuVXlxZWJ6b2h4OWsKLS0tIFVtRjZNUGMxZUFzVjBJNUlwNHRD
            d0VvTnpLYVpUZGxyZ3RZV2Y1czdRWW8Kuky3wb0hPwsmL862VmW8jtcuumPugr7F
            vNYhEqM6cHDNm5VV36axfl0ekuaFbP4pYDy6CKiMkrCrHqZMf83MNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T00:33:08Z"
    mac: ENC[AES256_GCM,data:AJ4Q5RWhnnCzL9Ksu/wHK2QTiO82XIryb17ZhqbJFgHOuOC5zG8svkLwYsFNEsAQbpfeEUTwaT5x+5ul5/Bep1Ey70n6l0pbhlJ2vwg32Ao5G4ZNzI7wcQZFD6LJI5mw6l0wLgX4Xo2PFkwvdFW/5+waoYaqeZmJWo8aUlk7e8E=,iv:LIaV8ywS1KT5WvXkjgMbzs3wGjkulAcxUAzyZ7W1Y14=,tag:4Wg++99oRhMPjZc1fh8KYw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
