apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:ErNnAoi0Ox0n3x/tWx4+vcIWvaA6PKFxZjsj5/ecMVUfZ+XLR2LLzA==,iv:Q0qVt4FsVIlyr77Ko+KZi59Ya/zCjAB58u9slkMSx/s=,tag:Z6834bFrKz7fgiGL26gIQQ==,type:str]
sops:
    age:
        - recipient: age18z3fy59zgysfr8jj3wlpsha2hjqjwm6glaes29wefxa3fadd6a4qnyh873
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQTZFZW5RLzdvNU5QUzNE
            OGVuNnFIbVVzTlpGMkdrM2hkbFV0WW9hYXl3CkRpSmxLL25rMzN0a3hOT2I5c3Zh
            UHNHUlM4UGhNSGtrdnVvdTJ5dVNRT1UKLS0tIHFpOS9hQXlIT2cxOXl4RmdSRUIz
            WFFVUDM4NzcrTCsybTA2UkN3a0l1V0EK8bINFERCMn3Eq+d6x0r1Y0f2E6j0kJCV
            2KAeYp8/PeDkuXshhYFu6hE+BkQBWubt9kjRMWEF/mS8yVqF50t8dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T16:52:56Z"
    mac: ENC[AES256_GCM,data:LJ/O6NHruIiecIy1dUtFg0FernBUHfuMjsK+KCyIfNgof4ox1jlPXS1zcWFRK7YqvWZDlCQ3nFGJsAAVyc9ZVP0oJfk5H5kXgHsG3yLEo/XmWMEDRbr1MMYiWmZbtpsQ+YgzBocX/DPO/HX2bWdURwiTvJ+g07OzyHv8ahQfRRE=,iv:eXzR+T1M6l3WDkRVIDae5KcFbMtqMkAeX7fsHM1wLmw=,tag:0D5FcsyrCdBtVEmKpK+LHA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
