apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dimp-migrate
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/dimp/overlays/prod-migrate
  force: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m

  dependsOn:
    - name: dimp-pg
