apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dimp
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/dimp/overlays/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  ignore: |
    kind: Secret
    name: dimp-auth-jwks
    namespace: dimp
    jsonPointers:
      - /data
      - /stringData

  dependsOn:
    - name: dimp-server-migrate
