apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dimp-pg
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/dimp/overlays/prod-pg
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
