apiVersion: v1
kind: Secret
metadata:
    name: flux-system
    namespace: flux-system
type: Opaque
stringData:
    identity: ENC[AES256_GCM,data:PzJk1YLRA5tEXpD9dReQyBVOLPKqq7a24TnxYNpl9l25imqylkluIVyUlvKOSQnFXjujArCBrGqSm349NRqp+9t1XjUfN+6bMCqW6digQFCpPT0g3pnIQNer/8Rm66pPQk9ohIqUXzq4NCf3xIfOZe5F4lfgfRGwnEaijsqYzWWt7YmI3C7vAP/WaDicI5nv/qWlQL2HtHOB+AzOyks8AKPdXW4AM6U0PTAnTmKayYoVTu9tYfpUGNY1r4jqL04LU3RqzhvpfxX6jaohFUS6/LvjYbiJHWx2nFCvmDyr3Un95hA8k9IIvISceZOt6tdTq7gXrMx4kP7pREEnIKyRDA1nf9kWRE4ya/FJ7kXIOxtr0d+ObqU58d5ScnQ/zpae/azNVcJH8G/plvuB6ImI6ebKY06gqPAo5TrN+pUqYHNBqnAwsq9ydHYAjJtIb1Ptrwo1zkz8r9aSL2xvsZt6fjreKsVG+JxrcogYcNSS2sMaCefoMS8niX/eUObFVq3uIm/nmXiKkhKKuzT0vZjPAwY=,iv:Pj/GNW023uAUr9z9Uzlo7jWCoqMwQUfKZMFMrn8YMJI=,tag:aA4ePz43MqxejhM1T9ENjw==,type:str]
    identity.pub: ENC[AES256_GCM,data:zlwKc8ow1Ou689qY6sv8h4kDYmPWMaWPUGpugXTm/TzuDs2giDym61Chho+/qnpXLm3GTAniFbSP9Ocb9I5osALu6dJQxjWDGiFj4Y6Ojmou2K6A9LEVbtEJTItilM8=,iv:Wcx5Zxlk3PGylLC4pLBGW1mNEgd7kuSGQJh96YWs7hs=,tag:OC6cIWGkCvMs5MiUpsSL9Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:TtcQWZJkXozk8BKE1wU6dNh6cXbmBPCZvfXb92MzWrSleyinzzt7RUtUB9w0qLfKiT87L+JztNJY/fP9ymmpvYNmxLo+HxRF4vrRvyZbgoXf0KAKdIqkt6NHNJI=,iv:JqCLQfn1ItemkYIsPt3QyBalXMAbrJiBz5pakgV8jJY=,tag:7ryeQFzpqthY5Sk/2eND3g==,type:str]
sops:
    age:
        - recipient: age18z3fy59zgysfr8jj3wlpsha2hjqjwm6glaes29wefxa3fadd6a4qnyh873
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqY0xBcW1ldjRwTi8rdDR0
            c2tTVnFEOXgwTWdRRjdzYWRwM1BNT0tpbEhFCkRaaHlYdm1qaW5yZXp4VWF5WWlR
            bWkxM3RoUmM5amxyMlEvWFkvbkh4Y0EKLS0tIEhROUxEdWZmUGhvVjVlSDNQNWhQ
            OGdnRmNmVlVKdjhjTk1oTUVuZno2K3MKkUtnSfzruSXAQj8ds4TilNi2SgaHwa5j
            nn4gC6r42SJbnJuqBveBUn44EbWmTKQa1hL3TEdw9YeG+evc/UVqkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T19:11:07Z"
    mac: ENC[AES256_GCM,data:43JypMNKlwvE3YRpwFyfdTZnfCF6qGih9fcSg0nG09G7dPTQEL2IUeRhEUb1aznPYnFQSe2tVc3IRwq3BlqsYx2C8OOSVJSmfepjgZNmRCaaOuOyECSxT+nVylXpCBwYdVx0iL6AB37mBG+RMM54xXTxeL/WhQ+vgNKyca2ExDY=,iv:Yj1lHXr8tFGA/a4aGwDf0HeTMuMz6BaQpnzqCdN+bLY=,tag:4BuG/falOWA3eLZxn7KatQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
