apiVersion: v1
kind: Secret
metadata:
    name: flux-system
    namespace: flux-system
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:N2C9zDONaQ==,iv:88znKUPcaa2eu153qsbN7ho+OXk6wD3YXpIDqQ0JQNE=,tag:H0t5LgAG2bA1l4XQ8EsXpA==,type:str]
    password: ENC[AES256_GCM,data:XwZkcOz4ok5gnPwHq+RJzZqHLAsTmVAmu5Ki4y6/C3tP6xG8MmFo2N0WwhnvdHniSv5dSFchrR1NzXRP+NiUsIFh+Bre4MMMXDDFCCJxIV6BR7LLIqxovmUAHV+Z,iv:IP0kHSSPcgqMaaTIoAnUjsH6mcmfQ3MtVwmOt18E6LI=,tag:4QMzcsJhyACUgwKWLPJafQ==,type:str]
sops:
    age:
        - recipient: age18z3fy59zgysfr8jj3wlpsha2hjqjwm6glaes29wefxa3fadd6a4qnyh873
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVUFHUW1lY2ltRloyM1Mw
            Q3dTYjZybFR6Z0s2cGdXL3lrQ3NKc1RRK1FzCmlyeFlPS0NvbGJBdlE4Z0JjWU9X
            ZUZueTczelY3S1JGQ3MvMTVaZGM3bEEKLS0tIGhzNkZUQktMQUVkcElNQnpRNTJn
            Umgvb2ZyZGlFK1BJbm9iWUNkaEFjZWsKT8HHMfwzf3wYG++wrce3UUgIfxnlPxMN
            aa9w+/vWcNa5Gqj9XY8iirRtWTftTIZpaPkv3gDd07DMehk1ziuCRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T04:59:11Z"
    mac: ENC[AES256_GCM,data:S8DqCucAWI0g06C34jfGqT3ql/rSALHxmqqoFQI0V/fZJ3inpXf6C+e3YaUE/yGgYQy8IK2q2dP77+mI1X2rlobUQSXDL4j9qv3v9c8lc9GfuLFQ8liL0DwA35KyBEsKIPlx3vbh6vLtxHTZ2ziZI8ET9YiZL8Wh3GHLgnYgVaw=,iv:CDwvT1+eGLvdYYqNpkuq0/Lsx/wwS8VoTqaj+NW9Q70=,tag:mWKrkJ+MRQ5mBiGJf8XgTg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
