---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: internship-observer
spec:
  schedule: "0 2 * * 1-5"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: internship-observer
              image: ghcr.io/williamwu277/observer
              envFrom:
                - secretRef:
                    name: internship-observer-secrets
              volumeMounts:
                - name: credentials
                  mountPath: /app/credentials.json
                  subPath: credentials.json
                  readOnly: true
              resources:
                requests:
                  cpu: 500m
                  memory: 512Mi
                limits:
                  cpu: 1000m
                  memory: 1Gi
          imagePullSecrets:
            - name: ghcr-pull-secret
          volumes:
            - name: credentials
              secret:
                secretName: internship-observer-credentials
