apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:V6tCuCjdE3SISW4RJBVcIllrg7mrpzt4vDCcn1cpH6x0Zl62woG0kdMui3EtbrVqeJ3buNmEgMaokxgUjTfXklV6qrxtgj+drq3ViHURC7eaWGLMu4W58MHE64qQzHdE+wocZHGS3nJWjpSxq4cEjl6W/fL9/6a35jab2BD91oKbZVjMOa79lPWKVMbN,iv:gbmqAh0ri9QTcQAsb8zlobyqn/VaMWDLXD3mB5T6kvg=,tag:eJFp1h+FVRcqJuy2llzVUg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTWM5U1RNSUE3NExhRjhv
            NkpvZG1RR01Fcno3cGZPYmtNZG02M3I1ZmtBCnVJKzhpZVprV2FTUnhLZDNYUnIr
            U29HUW92Zml2WEZYZ1FSY25VUGVBYTgKLS0tIHhlT1NTYUFFRHZMMTd5MTY5K0dx
            MThOWFJ0L2lvam5uV1hQNjNod200WGMKqno5fSIBJnG6ykTAeRYwiGkpWsFG4cyi
            ccCGK7MDihUxOoNy0YFw+HRTrh08FWRAysYjHjI5DcOBIhwKWDxLtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nkevsjrus2tls3xr2tf6wzypjzualle59evnrf9ucedphfkrmyxq9x569z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNlVUM0w4VjUrM012Mmtu
            d2hJUE1QV3lFVlhBUjA5Rll6RWI4STZLUkQ0CllTNWVBLzNOQVlxZHZ1dlFwSmlN
            bVc1VDhTNGcvRTZMYXExY2lZbzFDWXcKLS0tIC9NV01tMVR5MEFkblJTREVYTjFH
            V3lQaUVoK1BjeXZsUEZ1cWUxZFMzY0kK1RQwBVhfFLebsqPCHyNA7OkFyyZoggim
            DSCFaeYras2oHpxjPRvza2MA3xAAc5kyKGD/MQwANY5tRv9FxTL0iQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18z3fy59zgysfr8jj3wlpsha2hjqjwm6glaes29wefxa3fadd6a4qnyh873
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T15:06:45Z"
    mac: ENC[AES256_GCM,data:yRL3buLnbvMx61S2odeQKCrC/SnbNqhhBGYRVWOOAkYqCZRth50mszZBwXaiOEBuBjvlETHLre49H+vjAAfbvO3W2YhnhPZah6V2p9cFTdhXERtvmDTm1ifCny3EE7uJBDetDSSrlnzRabN4Vqcp7BeiakvdzBvFP9dOaqgfDvE=,iv:lCNxGg7TUL7Cin4hqG98B+oB0AQs0HCB3a+/zHXtQYs=,tag:pwT0JOys9Qot8i8d1qJG4A==,type:str]
    version: 3.13.1
