apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:mVK2uAn5dLKibOj8Rh+m9365xyG4EKoVBHVZSIdwEEtvW2+T45aJt/UClI1+YrJLqKkCEWUbSaaVkIX0Q83JGT2rP335Sm564I0NKFMVExAnf9xYAFD/Wk32BqlbmZxC7ZYLZaj+SAFL9brAETeeKn5oC7GVFmrsTFTfSggFz+lzfZ9kf9IERFpweMrt,iv:pM7qQyM77itILoKkNY+AbPmYZSlrp1tccafORU0+xAk=,tag:9z8hnG4n5Jjd1VV2yt3D+g==,type:str]
sops:
    age:
        - recipient: age18z3fy59zgysfr8jj3wlpsha2hjqjwm6glaes29wefxa3fadd6a4qnyh873
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSG1XcnhxUHRTNXhSR2Rz
            alpTMXdoaHNlOXpmandNZW90eFhZK1dKWUhZCnc2VFZjUXpuVnF0LzRuU3cvYUoz
            MlZwUUh3T0RaYlFMN3ZHWGZaQnVEZDQKLS0tIDNNeTZ2dDlBMDVNVzFtSVphcEZV
            d0NyVjRKQzhVK1VJQUI2NFBtZlF5TXMKGIK9GOR8EMTmInJa22bvU7aowciJ6OR5
            Q8SvzHtJ94siU17LY+ANaUliAMZ4Ltej85CdUEDYp4JxJH4X9AnChw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T23:01:45Z"
    mac: ENC[AES256_GCM,data:uYEz/HOXs3xWluM/WPdgRWDFXbZ/xou4Fu/guZa8Rl4JvwuKHc87Tr/LXm51YzxJqQwTAvjNxFzzoMbUl4RwaSW4ov8eRCurz05DNBBrN4nkRFhTqwSSLggE7cZIOTQ1FaQdjuNcSwzp2sora+VHlRGfLxwKyBYLDhSn3iJQmro=,iv:Gqh5yLnMrj+wCdlT0A79dQ712rXkrsO/0cGcKQRlsVs=,tag:aASK9o6fNHx513SIuo0AHA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
