# When updating this secret, please update the corresponding secret in cluster/flux-system/images/internship-observer/ghcr-pull-secret.enc.yaml as well.
apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:OZH7eyRhNsUxjBJnKeCDc9PG+iLSrQ0pdg3xfBGRuSnxi/6TAwg9Xz0aBSNj5sU1TyLZCOJe9L1+LP2CJT5H4tFmgZBFFSFEvDr9tMakDSKmJWEgoWtkE2RCgqn9PmcEK1aa4+iFj6RvmjcyugE3+VkT2WjRCwv/im0H6vrdjKwjs3UZz0o3xeLqDB3C,iv:iFqWUIm8rzS7aczgUeOusdHAP/rxwL7U3wgWXIOHJXI=,tag:X1NFC0bnfc9Ez7E1rrEa5A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUY0pkNVl0R0hnTlFyZHN2
            RjVsZ0U0R2lXOWFoUm90VlZJbFhuY2QwL253CjB4MTlSMjBCNUd4NXRXd2lqUk9w
            a0dSUFBZZHE3eTNNZWpKV0FxK1FabGMKLS0tIE95MzI4emNoNnlsdmRuSHpWTVZB
            UCtuWGtJd1BTYkJYNlJnTmVJTGV1ZjQKMYFHqQU/FT45fs67ZAzdJOiRsl8plhV0
            0AHCG1Jl8SstKlZ2A+r4LFK0vnut0J5fdt2S+xohDgnaH2nJ9udSrA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nkevsjrus2tls3xr2tf6wzypjzualle59evnrf9ucedphfkrmyxq9x569z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIY3J3bE43RDFRN0NtMXdu
            Vm91d0FnamNOSXVOOGhNVGNXWmtaWTRWRERzCnN2ck4wck5mcVd0RTZLendXbDRX
            WXY5K2ZMaTBqQ1pmRXJkWW9SYktIVjAKLS0tIFo1emtWa1FtMHByZmg0UXdXQm5q
            c1V4L2FYMjhYZEJBWGxvNEZnem83WlUKX2ahDQTjFwmIt6W5Rbkxr8vs30W3aZhA
            vindXbx3+zcDqVv1erFI6WcWTJFjFTfU+WZVfsUUfuvIDbQLqqJA2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18z3fy59zgysfr8jj3wlpsha2hjqjwm6glaes29wefxa3fadd6a4qnyh873
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T17:23:53Z"
    mac: ENC[AES256_GCM,data:VFydkhWUywSIdcAaRBWYTgsITHnyrAZdJDp9nDw+t0PlfqPQmavk7aNotsNBIpPyfm67OZHLb4QrRIlBZHVHehxWeIWQlzJimcB/0SwarwYrKTmNLJ/HT3YrSW0UXN2HD1sUWdV0NyDejAmHJoRS9kMR15sDe52uCZS+mlqUES0=,iv:yLZrRXxilqerY5tluPfL3QAhHUoEuwD+Jn9toQCUXwo=,tag:emvsH4wbDt03A59zqFkLbQ==,type:str]
    version: 3.13.1
