apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: internship-observer
resources:
  - namespace.yaml
  - secrets.enc.yaml
  - credentials-secret.enc.yaml
  - ghcr-pull-secret.enc.yaml
  - cronjob.yaml
images:
  - name: ghcr.io/williamwu277/observer
    newTag: latest
    digest: "sha256:9f7d495411bd90b1ef5136db64a46ec527991f34a7e1b058f79d4e3bc0b174e5" # {"$imagepolicy": "flux-system:internship-observer:digest"}
