apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: internship-observer
resources:
  - namespace.yaml
  - secrets.enc.yaml
  - credentials-secret.enc.yaml
  - ghcr-pull-secret.enc.yaml
  - cronjob.yaml
images:
  - name: ghcr.io/williamwu277/observer
    newTag: latest
    digest: "sha256:e8bdcd68b612d14cd0814ec93b0bbdd82ea8f3b9a94d281102eb7d221a8b7127" # {"$imagepolicy": "flux-system:internship-observer:digest"}
