apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: internship-observer
resources:
  - namespace.yaml
  - secrets.enc.yaml
  - credentials-secret.enc.yaml
  - ghcr-pull-secret.enc.yaml
  - cronjob.yaml
images:
  - name: ghcr.io/williamwu277/observer
    newTag: latest
    digest: "sha256:7e8ae52bac1075cacb45223d40a673151c93d4a08f6b6fe8ee3772a0c5e658f5" # {"$imagepolicy": "flux-system:internship-observer:digest"}
