apiVersion: v1
kind: Secret
metadata:
    name: internship-observer-secrets
type: Opaque
stringData:
    SPREADSHEET_ID: ENC[AES256_GCM,data:z7cUFnGcvoo/rZFZRA2LQ+1YJfIxFVOPUB655sTOkanj9LA4evsTr1D0lb4=,iv:K6+Y+0d6XLeq5txCzObAMm51GMLaoBNCSUWjNJLf7Ho=,tag:7GWsG2/stHod9gCmG627qw==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:WB+gOAj288IF/FJ8VkWmbxgGQkNF5tUIZXK2HsI80sWMQznrqVLv5vkBdVZQZfpqP1TITbSXTUH3WafZmCmv4oI+bbQOnlroEeqVTfDXC+xNf8RNTiaGNMK0m7UxOM0lWPmOL83Vvn++GNmB8N5VSrqKO+9AGvfI8Q==,iv:qfTLtp/sg6p5aBpqTiDYduHeNld4/rvGFQcCQHNUF+Q=,tag:DosZqUUwVhQvHQybm9kMUg==,type:str]
sops:
    age:
        - recipient: age18z3fy59zgysfr8jj3wlpsha2hjqjwm6glaes29wefxa3fadd6a4qnyh873
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdG42M3Rwd3hWM0hZUW9t
            S010Qlg0U1VsMXJLM05kVEJVeW1nL1o5VTFVCmNBaDhVdlY2c3NqaG0wbm9vT1ZM
            ekhHVE1jeXhRVUFnK2gwMHpTUUs2aVUKLS0tIE52QUY0aE56ZURUUlY0dE9zbzk1
            U1JPSVRFOXJKVWNYRUtWRU9QVkVTdkkKQ/+Et55IJanvTttPPO31P9LYK7K9c2Uc
            M0Aqa9mND+4UXc10yivzL7yuWpIDqu9w8SUgriqCUrHiE2cbZhbAKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T02:41:20Z"
    mac: ENC[AES256_GCM,data:zB3tU6uWRAJYa2p0KhRUJUGpYSjLbwKjkjAC3JuSwHcKU542cVVWGijtuKw+ssAMX9ukliRdcL9e9LbYG5yf+7NDKZ5sWnNggJWf+lRrUcCJNZdA/80Aw2GszzV4bXC1QklkliboYDbdotnaAGJLOOfU8cDRUg6+lM/74lntCs8=,iv:y1ferUuFZpoIXQnl9JgKmXhyfvBxdqhBIPU3BvmYH00=,tag:bcpPGrdqnzoy5Zah3OKSYQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
