apiVersion: v1
kind: Secret
metadata:
    name: internship-observer-secrets
type: Opaque
stringData:
    SPREADSHEET_ID: ENC[AES256_GCM,data:RefjIYaQoywZvseGWmmNPA3KbRSO6W6zphsFMXr4PcdvhXzLTaTdK/Vfj4c=,iv:aXcOeODHuU5Md2kHoqGTXPMhfUBw6H67vox/3hWWymQ=,tag:ob932auwX+duwZP9kOTWCA==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:Wya2rUTCjQRsj5zPpfQXU0V5ozkwE7wG9jofEejC1kb/11UdMGmTSdAqEjDWvL+pXVgEcw4wxt/rPIfs9S2CAVjB1aDrUyd9LNG6hZOglF/6Ygro9wI7Mg1j1HoFHbDRarvVee9Y6/OlK1+N10jM/2D9MGeShWAsLw==,iv:ae8QEwhuq1t/rDDhPZEAHOSBcQr6pbSJMRtbyCTpO/Q=,tag:mk5yMTn4KPcNg0Ob3ShL4g==,type:str]
sops:
    age:
        - recipient: age18z3fy59zgysfr8jj3wlpsha2hjqjwm6glaes29wefxa3fadd6a4qnyh873
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTHdEQnI3Z2RaQU9BWEw1
            Zm0wZ3hwSCtCNFB6NWdnL3JmYTlVdklpaVJFCk5nQkRsTjlaMjZrNVU3S1BYYzRG
            bDRHMHZSS2tDV0NTUjRBcGZVTSsyc0kKLS0tIEJhd0EvL3VSUWIwck9yL243WjAy
            RUFKVUwvUkVKcldJdHRrQnlHVGNZc0EKQe18hEHklbWGxBkds9P25EQ2pP5D2W2z
            TnnEERnE9pIboVbaDMEjpv1jkyI+u7aJYbHtD+/T4ZdnHjcRE4zLfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-28T00:23:06Z"
    mac: ENC[AES256_GCM,data:evy4AHXl5T0moA4ecS3J9EiCcQw1ScAzz72QDMb/pBGAf1MQprVsPg8KemPXBVVYIW2rTU23ZyQY4pgFPG2zuPctZCOojQDGSnCqgNv3xeRB8dTVzHmxsdBGHuc6Z1qMQMOA++VpCqM8TCFql2IaUcBxin+VOL6AimD0fF/3C0g=,iv:ZBMP7EgFRopnYrz9kwNs6z9qdeJZQ+eBDxG7eeEileA=,tag:RI0j0M3N7r9Q2JWbo7otBg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
