apiVersion: v1
kind: Secret
metadata:
    name: internship-observer-secrets
type: Opaque
stringData:
    SPREADSHEET_ID: ENC[AES256_GCM,data:B1x2O0+wWn3Ksv1Aw4vbrAczUX+Nt+uMPTYKq56EZbfu444V74OdRwt0SBE=,iv:f9p+IENT/rGNuXt25IZ63yO/Pq5bNQcd/LuNRMAe56k=,tag:janBf2U54ZB9mMxTrg4riA==,type:str]
    ANNOUNCEMENTS_WEBHOOK_URL: ENC[AES256_GCM,data:kWRZPJwc5i+ILkolMWOdnSx7EHieYCtrAiF7NP3FKP7n+ViqVcWaWnJixrd3YS1eSAoolghS/bWZd4z4agbngQgWzOaVEXyJFz0kkMQhDnx9nV5MKBFUVhdAli1oFNvWCZbEeUOA3rcqP5wihr+sJU0vxTRcy6supg==,iv:Y1/M9ZOfHDZlJtSEAAkOeRQcR2tOc746sCekfWlEhOc=,tag:l/ZttlF22Po19AYaI4vv7Q==,type:str]
    ERRORS_WEBHOOK_URL: ENC[AES256_GCM,data:inuHqfaF9PPpcwCJanJIuPVGPRVyWbsu8Qw3oQnBjbB78MSKDQ8eO0Le7XoJCeZg0o7TF1mBybrUsFw6EUitCe+JPk1Wy2NJlD80Tg1nl19CTcIRJ2TCxqUJGhy/2kX7FcVuX7ak2lbnlZ47tbJXf1QiBZ4MPOu+QA==,iv:6nBF0FlyXZzdAjnrKVmBQ+IIyKfQ1yGoB2OdbSK5vv4=,tag:G7ZeetMqi6H5DrVWzYKYlA==,type:str]
    SUMMARY_WEBHOOK_URL: ENC[AES256_GCM,data:+CGiw1muFlBAoBkVdBogtNVtdwXIhT9AxHM+IMDVZeV933zT4+oCd4YLmfHyadv6/PXnnceRXvXBvjaiqCVsgYHdzXNPzfXNqjezgTj9O3ElVdp1Et6TwZQhOX/9+X+uDEVIz5VE2WtqgEHWl0k8DXswE49yL2JHwA==,iv:JUiNgRr+FzqAIq7uCd/dHsZSeXRUOKsupb7YAkCic1Q=,tag:9UwZDtVUhBbZQOPuAXKhFw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbktPdklmNFVxR1cxSU1K
            enpxTXBmUEY3dUo4WHZKRG11WnlhOTZHamdJCnhSZ2RXdklka1VLZ1duTEZxV2Ir
            eFRSR2s1VmV5NjZkdndsdUJUbDJwOVUKLS0tIDQwczh2RmR2ck9QNlpFdnFadnZp
            czJSbkVvc0xzV0daNkVvTi96Vm1qRlUKHH4mRTfT/T8TqD2gcyqhNkqqO8q5WWWX
            OIDqXbLC03YMhj76cVZUDUddY24qr4eDWPz1fPTsFpDODJiuPPXtWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nkevsjrus2tls3xr2tf6wzypjzualle59evnrf9ucedphfkrmyxq9x569z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeVZuUFlLcXlnSlI0RVdP
            NTNnc3JFV01JRk5tUXZIcWdFazdVZWN3ckhJCkZoOGZuRGpuMzJxTXc4dkFQOHlj
            ZXhVSTNhMmlJQWVGRFExUlc3NzNGZFkKLS0tIG56YXk2ejROTHBmNGJHanpTU2w0
            dWZyRnlGdGZZUFdKVmFORExGV0lERXMKFsRxLZp6wOQEWVsO2FmzCfva+cWRT2S9
            05UZ6qd0/fzjkHiXFbkclwiqYqfnBBj6Unuc7EE8M77ZONiVU0WXzg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18z3fy59zgysfr8jj3wlpsha2hjqjwm6glaes29wefxa3fadd6a4qnyh873
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T17:47:14Z"
    mac: ENC[AES256_GCM,data:SXecRCk+hcBiboMqBra1u8zqh801ygepZpKGv/5ln1lAjPPU/41xlhvt6SRx0y7e4GvzT4iBDkfCz4uldyJvonjYC7EJsWgo88WFzh1v8B1oJfsLVj3+wVk7zewRuWr4mN7MofMmkTdNjh7GhEz2RrtvrLbSUcEx8i1828UD64I=,iv:rtfpIAxrQwgtxhJFrFPSR0UFyBdSv9n5kCp35ydOphg=,tag:uaCSnb5T2xv0KxdxtT4gWA==,type:str]
    version: 3.13.1
