---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: kbw-productsdisplay-api
  namespace: flux-system
spec:
  interval: 1m
  imageRepositoryRef:
    name: kbw-productsdisplay-api
  filterTags:
    pattern: "^latest$"
  policy:
    alphabetical:
      order: asc
  digestReflectionPolicy: Always
