apiVersion: v1
kind: Secret
metadata:
    name: kbw-productsdisplay-backup-secrets
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:E3DAcDNygeuGFZmofkOo6ySS1iSwHwKT5gugjcOLMm5TUzjcG4NgeKRG7CW8yJdqD+m58Udh+bk04R/ZQRlc8e08Vosb8WZjTmeuILoocPw9rDReOhZkC2xzgptySDBik0r8wLm+A9apt0ss27wCGA==,iv:xthYFyos55zkXICtuSJJQaoml+KP8OstJZsXxVqSSxo=,tag:P+HFirGBl46R2tFINQ/S9A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFc0hUR2Q5N2ZyREpLU0NU
            bnZsamlwT3QrdFY1emdwdE1rZ3hsd3Fwd3djCnB3ZWRKenhWSTI1WmxPd1BkZHE4
            ZlZOckNZZzNyVlNFVExHWHhrTXNkL2sKLS0tIFJxY0l0Q0lVSDA3MnRYYnFzU0JZ
            dmlTMWxNYTVMMUlzKytxM1RvZGg3MjQKWJPk0hAVkgW5IUSH6f2th+KR/IPPzhsz
            JlSKIqBFWA/ijYt6AqhctH9/PYag/qUB8a/YKHsGIaBPvTdJRjQvCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18z3fy59zgysfr8jj3wlpsha2hjqjwm6glaes29wefxa3fadd6a4qnyh873
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T21:35:57Z"
    mac: ENC[AES256_GCM,data:PCaug419Od7eX+H6q58q70Lzz+/j6ec2Gh0TXmd8o0XqzDp2lnd433hfG7erFQ4/Sfnz0LQMls/pZOr/KoUARv7wXE9HLonyw+gTJYy4UGqC+KDjGY8Rt/w2Z1h6wuAdZVWDAqwAb9wOQkx7AxSN3BLXY89uhC19l7lYFmog9rs=,iv:cXIsHFQcswAIwB79PVA+JpsSKNfCRAe1xzqIKBCReA4=,tag:cDLA6ApL6CLj2WrGcjckhQ==,type:str]
    version: 3.13.1
