apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kbw-productsdisplay-db-backups
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
