apiVersion: v1
kind: Secret
metadata:
    name: dimp-auth-secrets
type: Opaque
stringData:
    DISCORD_CLIENT_ID: ENC[AES256_GCM,data:vGbc9+h3VVknO7aa4kcEsJ4JDA==,iv:r/J7Rrm4Nn9QC+9N1RZCq5C/6eOChQJc0R9A7Hg93Lw=,tag:3ZSQjUE5RaXDZsY1Mvpn+Q==,type:str]
    DISCORD_OAUTH_TOKEN: ENC[AES256_GCM,data:0asQB/DbgdT0fp4Yx8vzJGukbtEw7xE51W5+MJUpFkY=,iv:5112tG6eoN24RQd2RLLDDx/uZ7DHzacDR2onuGI84a0=,tag:HM0W9heW5Zv/6S11RVw5zg==,type:str]
sops:
    age:
        - recipient: age18z3fy59zgysfr8jj3wlpsha2hjqjwm6glaes29wefxa3fadd6a4qnyh873
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeVpaL01WY2ZOTG5VQVFl
            RDFGUHpqVlEzYzNJVjUxZWQ0QjhiSHh3TVhRClJSSzUwbkFMakRvZnE3VUorWUwr
            dC90N1hrUCs5RGVndlhOR21JS2xRYjQKLS0tIDFOcXl6Q0dDNXMydVZzRis3NlJt
            SGVMQXBLQ2N2eEJNM0IwYkI2U2dWOE0K8TkC6CIr+dBy1zphfSC4FgdtpzsR0Rfo
            HG1ikJuBVeWCrcg3N/lY4N4CmijfOmvOnzPqFRcvLBQqKr0oae0lmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T22:50:20Z"
    mac: ENC[AES256_GCM,data:f/4XuyA1lvUjhHtoT9UgWnyeCvO4kG9BpfDRIDKZiUFctifT7RWIZ38PBHjugRNphVzYEi50oKi3BDVfVsSMD+5lyOrMgTpXO2L0wE9eJRm0tUFlhuyUh/vD3z4AZ6o5ZB8E/ljO3scogWOz82YZe2CicvrbkK1WALaSIWHvkQo=,iv:97GchTjjm6YxaVq1bF1FZLWb5NfDfsmw/hexkAprdJM=,tag:dP5G+QhwTu8AI14A3c5ESQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
