apiVersion: v1
kind: Secret
metadata:
    name: dimp-server-secrets
type: Opaque
stringData:
    DISCORD_CLIENT_ID: ENC[AES256_GCM,data:wo6eoHJTkgYeyx6NXpRxMGzoog==,iv:cTeHqzx6ry/tw/jgFPJl205nTXdaeAD6MnExO0o9NEw=,tag:xiLgysxYJ92dXxY64tgwXA==,type:str]
    OPENAI_API_KEY: ""
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:8alruieisFMdp54IXnu+ja5eEhQIZnKa8iEv7b08OW/oS1214o3B5hxwIKa750V82RAdxtE+FEFybrl1hWnoz+FVYRJEdoAZXEUM0MtI2dssk90j+EI81EfuOic7XX5ESKPnIhkniN+mW/qI,iv:EwElQzJ3in0+8BkgRuZ/W95tAWxd3OYvIZsR2aQ1q1o=,tag:oDfpI2au24YL+coulC4sbw==,type:str]
sops:
    age:
        - recipient: age18z3fy59zgysfr8jj3wlpsha2hjqjwm6glaes29wefxa3fadd6a4qnyh873
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbDFVNnpkRVhkeXFKZGtR
            K2ZmeXJCVGpDcnVMcWdjUkd4cVQ4Zmp6UlVvClRrelhESTJRaFZ1M2pRZXJxcjZz
            VDVQQk5GaU5wSk9IYXNWZFpjQldQYzAKLS0tIG5ZNGk0a0xXQ2RpNldZSFlNL0Ry
            amRjdHRrTVNSaVNtbGFtTXdZOWxUdE0K2X4eUqims5JsUl5n6eh/ReNyxb84CZIh
            c3DcHXDhGOdvxZCf0+bU5j8kGO0T1qHvqQooLo/av9gkpg5x5jAS4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T22:49:47Z"
    mac: ENC[AES256_GCM,data:ds6T43ghkV3l7dVLtli7r/20m8e9GxzihU9ZY+pBlSAKgjSz23657Mq04Un98O6Cnj6zEGIaexSuJHlNLuXCRwwyBw5tMyCsIDkOhuqcHuJ6kznP8AilYBvOtyQXTOL6GKtcqUOi9ZvTvia3koLYst/b/sAm0Dni8BQbZUzUJVc=,iv:HxN1leBzHuhWgqF6Sw5OzAiHSYje7hNx+qa1vHn7Bfw=,tag:iHa51h7tOGTPaEVgLQLIwg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
