apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dimp-staging
resources:
  - ../../base
patches:
  - path: dimp-auth-secrets.enc.yaml
  - path: dimp-bot-secrets.enc.yaml
  - path: dimp-server-secrets.enc.yaml
  - path: dimp-auth-env.patch.yaml
  - path: dimp-server-env.patch.yaml
images:
  - name: ghcr.io/1spyral/dimp-auth
    newTag: latest
    digest: sha256:44d6aab844eba2a696c9ca7a135b715b19b5cc463108e47902edb1cd6c7c166f # {"$imagepolicy": "flux-system:dimp-staging-auth:digest"}
  - name: ghcr.io/1spyral/dimp-bot
    newTag: latest
    digest: sha256:732e4ea6377d2cd19ee97a2f64596551d0592f7acdc60e879d30957501c4be68 # {"$imagepolicy": "flux-system:dimp-staging-bot:digest"}
  - name: ghcr.io/1spyral/dimp-dashboard
    newTag: latest
    digest: sha256:376e1a05dc91c1c76edba08d8085c8331d35f4065df9314d4d485faff8d82601 # {"$imagepolicy": "flux-system:dimp-staging-dashboard:digest"}
  - name: ghcr.io/1spyral/dimp-server
    newTag: latest
    digest: sha256:b6a11f94ea35162e60b193e735f371032df5fd6e3fc990cfb72a08565f630a80 # {"$imagepolicy": "flux-system:dimp-staging-server:digest"}
