apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dimp-staging
resources:
  - ../../base
patches:
  - path: dimp-auth-secrets.enc.yaml
  - path: dimp-bot-secrets.enc.yaml
  - path: dimp-server-secrets.enc.yaml
  - path: dimp-auth-env.patch.yaml
  - path: dimp-server-env.patch.yaml
images:
  - name: ghcr.io/1spyral/dimp-auth
    newTag: latest
    digest: sha256:8c33aedf86475c68110983f63a0822e13faa519af5bcb238b264d92d3743f74b # {"$imagepolicy": "flux-system:dimp-staging-auth:digest"}
  - name: ghcr.io/1spyral/dimp-bot
    newTag: latest
    digest: sha256:397e0feda5ea229ac8598e414f976f64595a3f10d180497d3c90237d2ee78de4 # {"$imagepolicy": "flux-system:dimp-staging-bot:digest"}
  - name: ghcr.io/1spyral/dimp-dashboard
    newTag: latest
    digest: sha256:cd39ee26a20e99bd09fddf51793bf544a83642576f7701ddf0279bff85a168f3 # {"$imagepolicy": "flux-system:dimp-staging-dashboard:digest"}
  - name: ghcr.io/1spyral/dimp-server
    newTag: latest
    digest: sha256:03a3976ba4cf70127c54803c050cdb2ddab5dc73a6925dae6ae69dc89a281171 # {"$imagepolicy": "flux-system:dimp-staging-server:digest"}
