apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dimp-staging
resources:
  - ../../base
patches:
  - path: dimp-auth-secrets.enc.yaml
  - path: dimp-bot-secrets.enc.yaml
  - path: dimp-server-secrets.enc.yaml
  - path: dimp-auth-env.patch.yaml
  - path: dimp-server-env.patch.yaml
images:
  - name: ghcr.io/1spyral/dimp-auth
    newTag: latest
    digest: sha256:38a5630f7652da3499abe4ffd1d7b855b5c7da8ae820f571f29ec814883edbc6 # {"$imagepolicy": "flux-system:dimp-staging-auth:digest"}
  - name: ghcr.io/1spyral/dimp-bot
    newTag: latest
    digest: sha256:4781f78fc66a672384c4697b87384dcb6123982f425c3daa8c512b67dd5cb657 # {"$imagepolicy": "flux-system:dimp-staging-bot:digest"}
  - name: ghcr.io/1spyral/dimp-dashboard
    newTag: latest
    digest: sha256:1c45b1a577328d76d7d7e384040594c3895404a0893d7120493bd438b385a74f # {"$imagepolicy": "flux-system:dimp-staging-dashboard:digest"}
  - name: ghcr.io/1spyral/dimp-server
    newTag: latest
    digest: sha256:bf5a6269e1c8a8c99898f9e2396815eb54203e15bee4beab34bab7d5cbf78fd9 # {"$imagepolicy": "flux-system:dimp-staging-server:digest"}
