apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pg
spec:
  interval: 30m
  chart:
    spec:
      chart: postgresql
      version: "15.*"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 12h

  values:
    fullnameOverride: pg

    primary:
      persistence:
        enabled: true
        size: 20Gi
