apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dimp-staging
resources:
  - ../../migrate
images:
  - name: ghcr.io/1spyral/dimp-auth-migrate
    newTag: latest
    digest: sha256:4d09cb5f3707c21a1fe7a4e36225f1a14c3b832d83f5b97b182339c34e9ed17c # {"$imagepolicy": "flux-system:dimp-staging-auth-migrate:digest"}
  - name: ghcr.io/1spyral/dimp-server-migrate
    newTag: latest
    digest: sha256:7358f5b2407cfdcaffb0aa0b892329d84cf7b161e967d9fbbf287ae0cececc24 # {"$imagepolicy": "flux-system:dimp-staging-server-migrate:digest"}
